---
- name: Webhook proxy url
  description: Go to https://smee.io/new set this to the URL that you are redirected to.
  env: WEBHOOK_PROXY_URL

- name: Webhook secret
  env: WEBHOOK_SECRET
  inputType: password

- name: App id
  description: The ID of your GitHub App
  env: APP_ID

- name: Private key
  env: PRIVATE_KEY
  inputType: textarea
